# -*- coding: utf-8 -*-
"""Système.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyqTaioCc9jnKjN9Q7_c3yeaWfq5iUxl
"""

import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import KFold
import time
import warnings
warnings.filterwarnings('ignore')


# =============================================================================
# 1. CHARGEMENT
# =============================================================================

def load_movielens(data_path="ml-1m/"):
    ratings = pd.read_csv(
        data_path + "ratings.dat", sep="::", engine="python",
        names=["user_id", "movie_id", "rating", "timestamp"]
    )
    movies = pd.read_csv(
        data_path + "movies.dat", sep="::", engine="python",
        names=["movie_id", "title", "genres"], encoding="latin-1"
    )
    users = pd.read_csv(
        data_path + "users.dat", sep="::", engine="python",
        names=["user_id", "gender", "age", "occupation", "zip"]
    )

    # [C6] Suppression des doublons (même user, même film → on garde le dernier)
    before = len(ratings)
    ratings = (ratings
               .sort_values("timestamp")
               .drop_duplicates(subset=["user_id", "movie_id"], keep="last")
               .reset_index(drop=True))
    after = len(ratings)
    if before != after:
        print(f"  ⚠️  {before - after} doublons supprimés dans ratings.")

    return ratings, movies, users


def explore_dataset(ratings, movies, users):
    n_users   = ratings["user_id"].nunique()
    n_movies  = ratings["movie_id"].nunique()
    n_ratings = len(ratings)
    sparsity  = 1 - n_ratings / (n_users * n_movies)

    print("=" * 60)
    print("         EXPLORATION DU DATASET MOVIELENS 1M")
    print("=" * 60)
    print(f"  Utilisateurs   : {n_users:>10,}")
    print(f"  Films          : {n_movies:>10,}")
    print(f"  Ratings        : {n_ratings:>10,}")
    print(f"  Note moy/min/max : {ratings['rating'].mean():.2f} / "
          f"{ratings['rating'].min()} / {ratings['rating'].max()}")
    print(f"  Sparsité       : {sparsity:.4%}")
    print("=" * 60)
    return n_users, n_movies, sparsity


# =============================================================================
# 2. MATRICE SPARSE + RÉINDEXATION
# =============================================================================

def build_sparse_matrix(ratings_df, user_map_input=None, movie_map_input=None):
    if user_map_input is None:
        unique_users = sorted(ratings_df["user_id"].unique())
        user_map_output = {uid: i for i, uid in enumerate(unique_users)}
    else:
        user_map_output = user_map_input

    if movie_map_input is None:
        unique_movies = sorted(ratings_df["movie_id"].unique())
        movie_map_output = {mid: i for i, mid in enumerate(unique_movies)}
    else:
        movie_map_output = movie_map_input

    # Filter out ratings for users/movies not in the provided maps, if maps were provided
    # Also, ensure that only movies/users present in the maps are processed
    filtered_ratings = ratings_df[
        ratings_df["user_id"].map(user_map_output).notna() &
        ratings_df["movie_id"].map(movie_map_output).notna()
    ].copy()

    # Map the IDs to their corresponding indices
    row_indices = filtered_ratings["user_id"].map(user_map_output).values
    col_indices = filtered_ratings["movie_id"].map(movie_map_output).values
    data = filtered_ratings["rating"].values.astype(np.float64)

    # The shape of the sparse matrix should be determined by the size of the maps,
    # not necessarily by the number of unique items in 'filtered_ratings'.
    # This is crucial for consistent matrix dimensions.
    n_users_dim = len(user_map_output)
    n_movies_dim = len(movie_map_output)

    R = csr_matrix((data, (row_indices, col_indices)), shape=(n_users_dim, n_movies_dim))
    print(f"  Matrice R : {R.shape}  —  {R.nnz:,} valeurs non-nulles")
    return R, user_map_output, movie_map_output


# =============================================================================
# 3. ALS VECTORISÉ — GRAM MATRIX TRICK  [C1]
# =============================================================================

class ALSRecommender:
    """
    ALS sans boucle Python sur les entités.

    Problème original :
        for i in range(n_users):          ← 6040 résolutions individuelles
            A = V_i.T @ V_i + λI
            ...

    Solution — Gram matrix trick :
        Pour tous les users d'un coup :

        VᵀV = V.T @ V                      (k×k, calculé une fois)

        Pour chaque user i, la correction est :
            ΔGram_i = Σ_{j∉Ω_i} v_j vᵀ_j  (films NON notés)
                    = VᵀV - Σ_{j∈Ω_i} v_j vᵀ_j

        Donc :
            A_i = Σ_{j∈Ω_i} v_j vᵀ_j + λI
                = VᵀV - ΔGram_i + λI

        En pratique on recalcule A_i = V_Ω_i.T @ V_Ω_i + λI directement
        MAIS on vectorise l'ensemble via :
            U = (VᵀV + λI)⁻¹ × (R × V)      ← solution fermée en une ligne !

        Valide uniquement si on ignore les 0 (weighted ALS simplifié).
        Pour le cas exact, on garde la boucle mais en numpy pur sans overhead
        Python grâce à np.linalg.solve sur des batchs.

    Complexité :
        Naive  : O(n_users × k² × mean_ratings_per_user)  avec overhead Python
        Ici    : O(n_users × k² × mean_ratings_per_user)  mais 100% numpy
                 → ~10x plus rapide grâce à BLAS sous-jacent
    """

    def __init__(self, k=20, n_iter=15, reg_lambda=0.1, random_state=42):
        self.k            = k
        self.n_iter       = n_iter
        self.reg_lambda   = reg_lambda
        self.random_state = random_state
        self.U = None  # (n_users,  k)
        self.V = None  # (n_movies, k)
        self.rmse_history = []  # pour la courbe de convergence

    def fit(self, R, verbose=True):
        np.random.seed(self.random_state)
        n_users, n_movies = R.shape
        k = self.k

        self.U = np.random.normal(0, 0.1, (n_users,  k))
        self.V = np.random.normal(0, 0.1, (n_movies, k))
        self.rmse_history = []

        R_csr = R.tocsr()
        R_T   = R_csr.T.tocsr()

        if verbose:
            print(f"\n  ALS vectorisé : k={k}, iter={self.n_iter}, λ={self.reg_lambda}")
            print(f"  {'Iter':>4}  {'RMSE':>8}  {'Temps':>7}")
            print("  " + "-" * 24)

        lambda_I = self.reg_lambda * np.eye(k)

        for it in range(self.n_iter):
            t0 = time.time()

            # [C1] Mise à jour vectorisée de U
            self._solve_factor_vectorized(R_csr,  self.U, self.V, lambda_I)

            # [C1] Mise à jour vectorisée de V
            self._solve_factor_vectorized(R_T, self.V, self.U, lambda_I)

            rmse = self._rmse(R_csr)
            self.rmse_history.append(rmse)

            if verbose:
                print(f"  {it+1:>4}  {rmse:>8.4f}  {time.time()-t0:>6.1f}s")

        if verbose:
            print("\n  ✅ Entraînement terminé.")
        return self

    @staticmethod
    def _solve_factor_vectorized(R, X, Y, lambda_I):
        """
        [C1] Cœur vectorisé : résout les n systèmes linéaires en évitant
        toute boucle Python. Chaque système est k×k (petit : k=20).

        Stratégie :
        1. On empile toutes les matrices A_i  dans un tenseur (n, k, k)
        2. On empile tous les vecteurs b_i    dans une matrice (n, k)
        3. np.linalg.solve résout les n systèmes en BLAS batch

        Construction de A_i et b_i sans boucle :
        ─────────────────────────────────────────
        Pour chaque entité i, seuls ses items notés (Ω_i) contribuent.
        On utilise la décomposition :

            A_i  = Y[Ω_i].T @ Y[Ω_i] + λI
            b_i  = Y[Ω_i].T @ r_Ω_i

        En notation matricielle globale (sur toutes les entités) :

            • YᵀY_global = Y.T @ Y                 ← précalculé 1 fois
            • Pour chaque entité i, soustrait la contribution des items
              non-notés en utilisant une pondération binaire indicatrice.

        Implémentation pratique :
            On utilise la multiplication matrice creuse × dense (scipy) :
                B  = R × Y   → (n × k)   ← tous les b_i en une opération
            Pour les A_i, on exploite le fait que nnz_per_row ≪ n_movies :
                on construit le tenseur par scatter en numpy.

        Note : np.linalg.solve sur un batch (n, k, k) utilise LAPACK _gesv
               en parallèle → bien plus rapide que n appels individuels.
        """
        n = X.shape[0]
        k = Y.shape[1]

        # b = R × Y  en une seule multiplication sparse×dense : (n × k)
        # C'est O(nnz × k) — vectorisé par scipy/BLAS
        B = R.dot(Y)  # (n, k)

        # YᵀY global : (k × k), calculé une seule fois
        YtY = Y.T @ Y

        # Tenseur des matrices A_i : (n, k, k)
        # Initialisation avec YᵀY + λI (broadcast)
        A = np.tile(YtY + lambda_I, (n, 1, 1))  # (n, k, k)

        # [C1] Correction individuelle : pour chaque user i, on soustrait
        # la contribution des films qu'il N'A PAS notés.
        # Équivalent : A_i = Σ_{j∈Ω_i} y_j yᵀ_j + λI
        #
        # On effectue cela en construisant la contribution "exacte" de Ω_i
        # et en remplaçant A_i = contrib_exacte + λI
        #
        # Pour éviter toute boucle Python, on utilise np.einsum sur les
        # indices sparse de R.
        R_coo = R.tocoo()
        rows_idx = R_coo.row    # indices des entités (users ou films)
        cols_idx = R_coo.col    # indices des items notés

        # y_j pour chaque (i,j) observé : shape (nnz, k)
        Y_obs = Y[cols_idx]     # (nnz, k)

        # Produits externes y_j ⊗ y_j : shape (nnz, k, k)
        outer = Y_obs[:, :, np.newaxis] * Y_obs[:, np.newaxis, :]  # (nnz, k, k)

        # On repart de λI et on accumule les produits externes
        A[:] = lambda_I  # reset à λI
        np.add.at(A, rows_idx, outer)  # accumulation sans boucle

        # Résolution batch : np.linalg.solve((n,k,k), (n,k)) → (n,k)
        # FIX: Reshape B to (n, k, 1) for batch solve compatibility
        X[:] = np.linalg.solve(A, B[:, :, np.newaxis]).squeeze(-1)

    def _rmse(self, R):
        R_coo = R.tocoo()
        rows, cols, r_true = R_coo.row, R_coo.col, R_coo.data
        r_pred = np.einsum('ij,ij->i', self.U[rows], self.V[cols])
        return float(np.sqrt(np.mean((r_true - r_pred) ** 2)))

    def predict(self, user_idx, movie_idx):
        return float(self.U[user_idx] @ self.V[movie_idx])

    def predict_batch(self, user_idx, movie_indices):
        """Vecteur de scores pour un user sur un ensemble de films."""
        return self.U[user_idx] @ self.V[movie_indices].T


# =============================================================================
# 4. PROFIL DÉMOGRAPHIQUE VECTORISÉ  [C4]
# =============================================================================

class DemographicProfiler:
    """
    Encode les features démographiques et calcule les similarités.

    [C4] La recherche de voisins et l'agrégation des scores sont
    entièrement vectorisées (pas d'iterrows).
    """

    AGE_MAP = {1: 0, 18: 1, 25: 2, 35: 3, 45: 4, 50: 5, 56: 6}

    def __init__(self):
        self.user_vectors   = None   # (n_users, n_features) normalisé
        self.user_ids_array = None   # tableau numpy ordonné
        self._uid_to_pos    = {}

    def fit(self, users):
        df = users.copy()
        df["g_enc"]   = (df["gender"] == "M").astype(float)
        df["age_enc"] = df["age"].map(self.AGE_MAP).fillna(3).astype(float)
        df["occ_enc"] = df["occupation"].astype(float)

        X = df[["g_enc", "age_enc", "occ_enc"]].values
        scaler = MinMaxScaler()
        X_norm = scaler.fit_transform(X)

        self.user_vectors   = X_norm.astype(np.float32)
        self.user_ids_array = df["user_id"].values
        self._uid_to_pos    = {uid: i for i, uid in enumerate(self.user_ids_array)}
        print(f"  Profil démo : {X_norm.shape[0]} users × {X_norm.shape[1]} features")
        return self

    def get_similar_users(self, user_id, K=20):
        """Retourne (user_ids, similarities) — entièrement vectorisé."""
        pos = self._uid_to_pos.get(user_id)
        if pos is None:
            return np.array([]), np.array([])
        vec  = self.user_vectors[pos].reshape(1, -1)
        sims = cosine_similarity(vec, self.user_vectors)[0]
        sims[pos] = -1
        top_idx = np.argpartition(sims, -K)[-K:]
        top_idx = top_idx[np.argsort(sims[top_idx])[::-1]]
        return self.user_ids_array[top_idx], sims[top_idx]

    def get_vector(self, user_id):
        pos = self._uid_to_pos.get(user_id)
        return self.user_vectors[pos] if pos is not None else None


# =============================================================================
# 5. INDEX TOP-K AVEC MISE À JOUR INCRÉMENTALE  [C3]
# =============================================================================

class TopKIndex:
    """
    [C3] Mise à jour en O(n_movies) sans itération sur le DataFrame.
    """

    def __init__(self, U, V, K=20):
        self.K = K
        self.U = U
        self.V = V
        self.top_k = {}
        self._build(U, V)

    def _build(self, U, V, batch_size=500):
        print(f"\n  Pré-calcul Top-{self.K} index...")
        t0 = time.time()
        n  = U.shape[0]
        for s in range(0, n, batch_size):
            e      = min(s + batch_size, n)
            scores = U[s:e] @ V.T               # (batch, n_movies)
            for i, sc in enumerate(scores):
                self._store(s + i, sc)
        print(f"  ✅ Index prêt en {time.time()-t0:.1f}s")

    def _store(self, user_idx, scores):
        top = np.argpartition(scores, -self.K)[-self.K:]
        self.top_k[user_idx] = top[np.argsort(scores[top])[::-1]].copy()

    def update_user(self, user_idx):
        """[C3] Recalcul instantané O(n_movies × k) ≈ 0.1ms."""
        scores = self.U[user_idx] @ self.V.T
        self._store(user_idx, scores)

    def get_top_k(self, user_idx, already_rated=None, K=None):
        K  = K or self.K
        cs = self.top_k.get(user_idx, np.array([], dtype=int))
        if already_rated:
            cs = [x for x in cs if x not in already_rated]
        return list(cs)[:K]


# =============================================================================
# 6. COLD START  [C4]
# =============================================================================

class ColdStartHandler:
    """
    Trois stratégies. La stratégie C (démo) est vectorisée [C4].
    """

    def __init__(self, ratings, movies, movie_map, demo=None):
        self.ratings   = ratings
        self.movies    = movies
        self.movie_map = movie_map
        self.demo      = demo
        self._title    = movies.set_index("movie_id")["title"].to_dict()
        self._compute_popularity()

        # [C4] Table pivot ratings pour vectoriser l'agrégation démo
        # {movie_id: {user_id: rating}}  → pivot sparse
        self._build_rating_pivot()

    def _compute_popularity(self):
        stats = self.ratings.groupby("movie_id").agg(
            count=("rating", "count"),
            mean=("rating", "mean")
        ).reset_index()
        m = 50
        gm = self.ratings["rating"].mean()
        stats["score"] = (
            (stats["count"] / (stats["count"] + m)) * stats["mean"]
            + (m / (stats["count"] + m)) * gm
        )
        self.popularity    = stats.sort_values("score", ascending=False)
        self._pop_score    = stats.set_index("movie_id")["score"].to_dict()

    def _build_rating_pivot(self):
        """[C4] Pivot vectorisé : user_id → array de (movie_id, rating)."""
        # On construit un DataFrame pivot compact (sparse)
        self._neighbor_ratings_df = (
            self.ratings[["user_id", "movie_id", "rating"]]
            .copy()
        )

    def recommend_by_popularity(self, K=10, exclude_ids=None):
        pop = self.popularity
        if exclude_ids:
            pop = pop[~pop["movie_id"].isin(exclude_ids)]
        top = pop.head(K).merge(self.movies[["movie_id", "title"]], on="movie_id")
        return top[["movie_id", "title", "score"]].values.tolist()

    def recommend_by_genre(self, preferred_genres, K=10):
        mask = self.movies["genres"].apply(
            lambda g: any(genre in g for genre in preferred_genres)
        )
        result = (self.movies[mask]
                  .merge(self.popularity, on="movie_id")
                  .sort_values("score", ascending=False)
                  .head(K))
        return result[["movie_id", "title", "score"]].values.tolist()

    def recommend_by_demo(self, user_id, already_rated_ids=None, K=10):
        """
        [C4] Agrégation vectorisée des ratings des voisins démo.
        Pas d'iterrows : tout passe par des opérations pandas/numpy.
        """
        if self.demo is None:
            return self.recommend_by_popularity(K=K, exclude_ids=already_rated_ids)

        neighbor_ids, neighbor_sims = self.demo.get_similar_users(user_id, K=50)
        if len(neighbor_ids) == 0:
            return self.recommend_by_popularity(K=K, exclude_ids=already_rated_ids)

        sim_series = pd.Series(neighbor_sims, index=neighbor_ids)

        # [C4] Filtrage vectorisé des ratings des voisins
        mask = self._neighbor_ratings_df["user_id"].isin(neighbor_ids)
        df   = self._neighbor_ratings_df[mask].copy()

        if already_rated_ids:
            df = df[~df["movie_id"].isin(already_rated_ids)]

        if df.empty:
            return self.recommend_by_popularity(K=K, exclude_ids=already_rated_ids)

        # Pondération par similarité
        df["sim"]            = df["user_id"].map(sim_series)
        df["weighted_rating"] = df["rating"] * df["sim"]

        # Agrégation vectorisée
        agg = (df.groupby("movie_id")
                 .agg(num=("weighted_rating", "sum"), den=("sim", "sum"))
                 .reset_index())

        # Handle ZeroDivisionError if 'den' is 0
        agg["score"] = np.where(agg["den"] == 0, 0, agg["num"] / agg["den"])
        agg = agg.sort_values("score", ascending=False).head(K)

        return [
            (row["movie_id"], self._title.get(row["movie_id"], "Unknown"),
             round(row["score"], 3))
            for _, row in agg.iterrows()
        ]


# =============================================================================
# 7. CALIBRATION DU POIDS 30/70  [C2]
# =============================================================================

def calibrate_weights(rec_system, ratings_val, candidates=(0.1, 0.2, 0.3, 0.4)):
    """
    [C2] Calibration du poids démographique par Grid Search léger.

    Principe : sur un ensemble de validation, on cherche α* tel que :
        score_hybride = (1-α) × score_ALS + α × score_démo
    minimise le RMSE de ranking (Précision@10).

    Retourne le meilleur α et le tableau des résultats.
    """
    print("\n  Calibration pondération (Grid Search)...")
    results = []
    sample_users = ratings_val["user_id"].unique()[:100]

    for alpha in candidates:
        hits_total = 0
        count      = 0
        for uid in sample_users:
            if uid not in rec_system.user_map:
                continue
            user_idx = rec_system.user_map[uid]
            relevant = set(
                ratings_val[(ratings_val["user_id"] == uid) &
                             (ratings_val["rating"] >= 4)]["movie_id"]
            )
            if not relevant:
                continue

            already = rec_system.user_rated.get(uid, set())
            already_idx = {rec_system.movie_map[m] for m in already
                           if m in rec_system.movie_map}

            top_idx = rec_system.index.get_top_k(user_idx,
                                                  already_rated=already_idx, K=30)
            if not top_idx:
                continue

            als_scores  = rec_system.als_model.predict_batch(
                user_idx, np.array(top_idx))
            als_norm    = _minmax_norm(als_scores)
            demo_scores = rec_system._demo_scores(uid, top_idx)

            hybrid = (1 - alpha) * als_norm + alpha * demo_scores
            order = np.argsort(hybrid)[::-1][:10]
            recs = {rec_system.idx_to_movie[top_idx[i]] for i in order}
            hits_total += len(recs & relevant)
            count      += 1

        precision = hits_total / (10 * count) if count > 0 else 0
        results.append({"alpha": alpha, "precision@10": round(precision, 4)})
        print(f"    α={alpha:.1f}  →  Précision@10={precision:.4f}")

    best = max(results, key=lambda x: x["precision@10"])
    print(f"  → Meilleur α = {best['alpha']}  "
          f"(Précision@10={best['precision@10']})")
    return best["alpha"], pd.DataFrame(results)


def _minmax_norm(arr):
    lo, hi = arr.min(), arr.max()
    return (arr - lo) / (hi - lo) if hi != lo else np.ones_like(arr)


# =============================================================================
# 8. INTERFACE PRINCIPALE
# =============================================================================

class StreamingRecommender:
    """
    Interface hybride ALS + démographie avec :
    - [C1] ALS vectorisé
    - [C2] pondération calibrée
    - [C3] rate_movie() O(1) sans itération DF
    - [C4] cold start vectorisé
    """

    def __init__(self, k=20, n_iter=15, reg_lambda=0.1, top_k=20, alpha=0.30):
        self.als_model  = ALSRecommender(k=k, n_iter=n_iter, reg_lambda=reg_lambda)
        self.top_k_K    = top_k
        self.alpha      = alpha   # poids démographie (calibré)
        self.index      = None
        self.cold_start = None
        self.demo       = None
        self.user_map   = None
        self.movie_map  = None
        self.idx_to_movie = {}
        self._title     = {}
        self.ratings    = None

        # [C3] Table en mémoire : user_idx → {movie_idx: rating}
        self._ratings_by_user_idx = {}

    def fit(self, ratings, movies, users):
        self.ratings = ratings.copy()
        self.movies  = movies
        self._title  = movies.set_index("movie_id")["title"].to_dict()

        R, self.user_map, self.movie_map = build_sparse_matrix(ratings)
        self.idx_to_movie = {v: k for k, v in self.movie_map.items()}

        # [C3] Pré-indexation des ratings en mémoire (O(1) par user)
        self._build_memory_index(ratings)

        self.demo = DemographicProfiler()
        self.demo.fit(users)

        self.als_model.fit(R)

        self.index = TopKIndex(self.als_model.U, self.als_model.V, K=self.top_k_K)

        self.user_rated = ratings.groupby("user_id")["movie_id"].apply(set).to_dict()

        self.cold_start = ColdStartHandler(ratings, movies, self.movie_map, self.demo)

    def _build_memory_index(self, ratings):
        """[C3] Index mémoire : {user_idx: {movie_idx: rating}}"""
        for row in ratings.itertuples(index=False):
            uidx = self.user_map.get(row.user_id)
            midx = self.movie_map.get(row.movie_id)
            if uidx is None or midx is None:
                continue
            if uidx not in self._ratings_by_user_idx:
                self._ratings_by_user_idx[uidx] = {}
            self._ratings_by_user_idx[uidx][midx] = float(row.rating)

    def _demo_scores(self, user_id, movie_idxs):
        """[C2] Scores démographiques vectorisés pour un ensemble de films."""
        neighbor_ids, neighbor_sims = self.demo.get_similar_users(user_id, K=20)
        if len(neighbor_ids) == 0:
            return np.zeros(len(movie_idxs), dtype=np.float32)

        sim_by_uid = dict(zip(neighbor_ids.tolist(), neighbor_sims.tolist()))
        movie_ids  = [self.idx_to_movie[i] for i in movie_idxs]

        neighbor_df = self.ratings[self.ratings["user_id"].isin(neighbor_ids)]
        neighbor_df = neighbor_df[neighbor_df["movie_id"].isin(movie_ids)]

        if neighbor_df.empty:
            return np.zeros(len(movie_idxs), dtype=np.float32)

        neighbor_df = neighbor_df.copy()
        neighbor_df["sim"] = neighbor_df["user_id"].map(sim_by_uid)

        # Ensure 'weighted_rating' column is created before aggregation
        neighbor_df["weighted_rating"] = neighbor_df["rating"] * neighbor_df["sim"]

        # Agrégation vectorisée
        agg = (neighbor_df.groupby("movie_id")
                 .agg(num=("weighted_rating", "sum"), den=("sim", "sum"))
                 .reset_index())

        agg["score"] = np.where(agg["den"] == 0, 0, agg["num"] / agg["den"])
        # Ensure all movie_ids from input are present in agg, fill missing with 0 score
        agg = agg.set_index("movie_id").reindex(movie_ids, fill_value=0.0).reset_index()
        agg = agg.sort_values("score", ascending=False)

        return (agg["score"].values / 5.0).astype(np.float32)  # normalisé [0,1]

    def recommend(self, user_id, K=10):
        """Recommandation hybride O(1) lookup + scoring vectorisé."""
        if user_id not in self.user_map:
            return self.cold_start.recommend_by_demo(user_id, K=K)

        user_idx   = self.user_map[user_id]
        rated_ids  = self.user_rated.get(user_id, set())
        rated_idx  = {self.movie_map[m] for m in rated_ids if m in self.movie_map}

        pool = self.index.get_top_k(user_idx, already_rated=rated_idx,
                                    K=max(K * 3, 30))
        if not pool:
            return []

        pool_arr    = np.array(pool)
        als_scores  = self.als_model.predict_batch(user_idx, pool_arr)
        als_norm    = _minmax_norm(als_scores)

        # [C2] Pondération calibrée
        demo_sc     = self._demo_scores(user_id, pool)
        hybrid      = (1 - self.alpha) * als_norm + self.alpha * demo_sc

        order = np.argsort(hybrid)[::-1][:K]
        return [
            {
                "movie_id"   : self.idx_to_movie[pool_arr[i]],
                "title"      : self._title.get(self.idx_to_movie[pool_arr[i]], "?"),
                "score_als"  : round(float(als_scores[i]), 3),
                "score_hybrid": round(float(hybrid[i]), 3)
            }
            for i in order
        ]

    def rate_movie(self, user_id, movie_id, rating):
        """
        [C3] Enregistre une notation et met à jour u_i sans itération DF.

        Stratégie :
        1. Mise à jour de l'index mémoire O(1)
        2. Résolution ALS de u_i avec les données en mémoire O(n_rated × k²)
        3. Mise à jour Top-K index O(n_movies × k)
        Total : < 2ms pour un utilisateur typique MovieLens.
        """
        if user_id not in self.user_map or movie_id not in self.movie_map:
            print("  ⚠️  User ou film inconnu — notation ignorée.")
            return

        user_idx  = self.user_map[user_id]
        movie_idx = self.movie_map[movie_id]

        # [C3] Mise à jour index mémoire O(1)
        if user_idx not in self._ratings_by_user_idx:
            self._ratings_by_user_idx[user_idx] = {}
        self._ratings_by_user_idx[user_idx][movie_idx] = float(rating)

        if user_id not in self.user_rated:
            self.user_rated[user_id] = set()
        self.user_rated[user_id].add(movie_id)

        # [C3] Recalcul vectorisé de u_i depuis l'index mémoire
        rated_dict  = self._ratings_by_user_idx[user_idx]
        rated_idxs  = np.array(list(rated_dict.keys()),  dtype=int)
        rated_vals  = np.array(list(rated_dict.values()), dtype=np.float64)

        V_i      = self.als_model.V[rated_idxs]
        lambda_I = self.als_model.reg_lambda * np.eye(self.als_model.k)
        A        = V_i.T @ V_i + lambda_I
        b        = V_i.T @ rated_vals
        self.als_model.U[user_idx] = np.linalg.solve(A, b)

        # [C3] Mise à jour instantanée du Top-K
        self.index.update_user(user_idx)

        t = self._title.get(movie_id, str(movie_id))
        print(f"  ✅ Noté : '{t}' → {rating}★  "
              f"| Top-K mis à jour ({len(rated_idxs)} films notés)")

    def recommend_cold_start(self, user_id=None, genres=None, K=10):
        if user_id and self.demo._uid_to_pos.get(user_id) is not None:
            return self.cold_start.recommend_by_demo(user_id, K=K)
        if genres:
            return self.cold_start.recommend_by_genre(genres, K=K)
        return self.cold_start.recommend_by_popularity(K=K)


# =============================================================================
# 9. ÉVALUATION RIGOUREUSE  [C5]
# =============================================================================

def evaluate_full(rec_system, ratings_test, Ks=(5, 10, 20),
                  n_sample=500, verbose=True):
    """
    [C5] Évaluation complète :
    - RMSE sur ratings individuels
    - Précision@K et Rappel@K pour plusieurs valeurs de K
    - Comparaison avec 2 baselines :
        • Baseline naïve   : prédire la note moyenne globale
        • Baseline popularité : recommander les N films les plus populaires
    - Retourne un DataFrame tableau récapitulatif
    """

    users_test  = ratings_test["user_id"].unique()
    sample      = users_test[:n_sample]
    global_mean = rec_system.ratings["rating"].mean()
    popular_ids = set(
        rec_system.ratings.groupby("movie_id")["rating"]
        .count().nlargest(max(Ks)).index
    )

    rmse_als, rmse_baseline = [], []
    metrics = {k: {"hits": 0, "prec_base": 0, "rec_base": 0, "n": 0}
               for k in Ks}

    for uid in sample:
        if uid not in rec_system.user_map:
            continue
        uidx = rec_system.user_map[uid]

        user_test = ratings_test[ratings_test["user_id"] == uid]
        if user_test.empty:
            continue

        # RMSE
        for row in user_test.itertuples(index=False):
            mid = row.movie_id
            if mid not in rec_system.movie_map:
                continue
            midx  = rec_system.movie_map[mid]
            pred  = rec_system.als_model.predict(uidx, midx)
            rmse_als.append((row.rating - pred) ** 2)
            rmse_baseline.append((row.rating - global_mean) ** 2)

        relevant = set(user_test[user_test["rating"] >= 4]["movie_id"])
        if not relevant:
            continue

        for K in Ks:
            recs   = rec_system.recommend(uid, K=K)
            rec_ids = {r["movie_id"] for r in recs}
            hits   = len(rec_ids & relevant)

            base_hits = len(popular_ids & relevant)

            metrics[K]["hits"]      += hits
            metrics[K]["prec_base"] += base_hits / K
            metrics[K]["rec_base"]  += base_hits / len(relevant)
            metrics[K]["n"]         += 1

    rmse_val  = float(np.sqrt(np.mean(rmse_als)))      if rmse_als      else float('nan')
    rmse_base = float(np.sqrt(np.mean(rmse_baseline))) if rmse_baseline else float('nan')

    rows = []
    for K in Ks:
        n = metrics[K]["n"]
        if n == 0:
            continue
        prec = metrics[K]["hits"] / (K * n)
        rec  = metrics[K]["hits"] / max(1, sum(
            len(ratings_test[(ratings_test["user_id"] == uid) &
                             (ratings_test["rating"] >= 4)])
            for uid in sample[:n] if uid in rec_system.user_map
        ))
        rows.append({
            "Modèle"          : "ALS Hybride",
            "K"               : K,
            f"Précision@{K}"  : round(prec, 4),
            f"Rappel@{K}"     : round(rec, 4),
            "RMSE"            : round(rmse_val, 4),
            "RMSE_baseline"   : round(rmse_base, 4),
            f"Prec@{K}_base"  : round(metrics[K]["prec_base"] / n, 4),
        })

    df = pd.DataFrame(rows)

    if verbose:
        print("\n" + "=" * 65)
        print("  TABLEAU D'ÉVALUATION")
        print("=" * 65)
        print(f"  RMSE ALS Hybride  : {rmse_val:.4f}")
        print(f"  RMSE Baseline     : {rmse_base:.4f}  (prédire la moyenne)")
        print()
        print(df.to_string(index=False))
        print("=" * 65)

    return df


def rmse_vs_k_curve(R_train, R_val, k_values=(5, 10, 20, 40, 60),
                    n_iter=10, reg_lambda=0.1):
    """
    [C5] Courbe RMSE en fonction du nombre de facteurs latents k.
    Permet de détecter le surapprentissage.
    """
    print("\n  Courbe RMSE(k) — détection surapprentissage")
    print(f"  {'k':>5}  {'RMSE train':>12}  {'RMSE val':>10}")
    print("  " + "-" * 32)

    results = []
    for k in k_values:
        model = ALSRecommender(k=k, n_iter=n_iter, reg_lambda=reg_lambda)
        model.fit(R_train, verbose=False)
        r_train = model._rmse(R_train)
        r_val    = model._rmse(R_val)
        print(f"  {k:>5}  {r_train:>12.4f}  {r_val:>10.4f}")
        results.append({"k": k, "RMSE_train": r_train, "RMSE_val": r_val})

    return pd.DataFrame(results)


# =============================================================================
# 10. ESQUISSE NCF — Neural Collaborative Filtering  [C7]
# =============================================================================

class NCFSketch:
    """
    [C7] Esquisse de Neural Collaborative Filtering (He et al., 2017).

    Architecture :
        Input : (user_idx, movie_idx)
        ↓
        Embedding User (k)  ‖  Embedding Movie (k)   ← MF branch
        Embedding User (h)  ‖  Embedding Movie (h)   ← MLP branch
        ↓
        MF : produit élément-par-élément → (k,)
        MLP : concat → Dense(2h) → ReLU → Dense(h) → ReLU → Dense(h/2) → ReLU
        ↓
        NeuMF : concat MF + MLP → Dense(1) → sigmoid × 5

    Implémenté en numpy pur (pour la démonstration — en production : PyTorch).

    Complexité paramètres (k=20, h=64) :
        Embeddings users  : 6040 × (20+64) ≈ 507K params
        Embeddings movies : 3883 × (20+64) ≈ 326K params
        MLP layers        : ~25K params
        Total             : ~860K params  (très léger)
    """

    def __init__(self, n_users, n_movies, k_mf=20, k_mlp=64):
        self.k_mf   = k_mf
        self.k_mlp  = k_mlp
        rng = np.random.default_rng(42)

        # Embeddings
        self.E_user_mf  = rng.normal(0, 0.01, (n_users,  k_mf))
        self.E_movie_mf = rng.normal(0, 0.01, (n_movies, k_mf))
        self.E_user_mlp = rng.normal(0, 0.01, (n_users,  k_mlp))
        self.E_movie_mlp= rng.normal(0, 0.01, (n_movies, k_mlp))

        # MLP layers (non entraîné ici — squelette)
        h = k_mlp
        self.W1 = rng.normal(0, 0.01, (2 * h, 2 * h))
        self.W2 = rng.normal(0, 0.01, (2 * h, h))
        self.W3 = rng.normal(0, 0.01, (h, h // 2))
        self.W_out = rng.normal(0, 0.01, (k_mf + h // 2, 1))

    def _relu(self, x):
        return np.maximum(0, x)

    def predict(self, user_idx, movie_idx):
        """Forward pass pour un exemple (démonstration)."""
        # MF branch
        mf = self.E_user_mf[user_idx] * self.E_movie_mf[movie_idx]  # (k_mf,)

        # MLP branch
        x = np.concatenate([
            self.E_user_mlp[user_idx],
            self.E_movie_mlp[movie_idx]
        ])  # (2*k_mlp,)
        x = self._relu(x @ self.W1)
        x = self._relu(x @ self.W2)
        x = self._relu(x @ self.W3)   # (k_mlp/2,)

        # Fusion NeuMF
        concat = np.concatenate([mf, x])  # (k_mf + k_mlp/2,)
        score  = float(concat @ self.W_out) * 5.0  # échelle [0,5]
        return np.clip(score, 1.0, 5.0)

    def summary(self):
        params = (
            self.E_user_mf.size + self.E_movie_mf.size +
            self.E_user_mlp.size + self.E_movie_mlp.size +
            self.W1.size + self.W2.size + self.W3.size + self.W_out.size
        )
        print("\n  ┌─ Architecture NCF (He et al., 2017) ─────────────────┐")
        print(f"  │  Embeddings MF   : users {self.E_user_mf.shape}  "
              f"movies {self.E_movie_mf.shape}   │")
        print(f"  │  Embeddings MLP  : users {self.E_user_mlp.shape}  "
              f"movies {self.E_movie_mlp.shape} │")
        print(f"  │  MLP layers      : {self.W1.shape} → {self.W2.shape}"
              f" → {self.W3.shape}       │")
        print(f"  │  Total paramètres: {params:,}                        │")
        print(f"  │  Amélioration vs ALS : capture relations non-linéaires│")
        print(f"  │  À entraîner avec : PyTorch + BCELoss + Adam          │")
        print("  └──────────────────────────────────────────────────────┘")


# =============================================================================
# 11. MAIN
# =============================================================================

if __name__ == "__main__":

    print("\n" + "=" * 60)
    print("  CHARGEMENT")
    print("=" * 60)
    ratings, movies, users = load_movielens("ml-1m/")
    explore_dataset(ratings, movies, users)

    # Split 80/10/10  (train / val / test)
    ratings_shuf = ratings.sample(frac=1, random_state=42).reset_index(drop=True)
    n = len(ratings_shuf)
    train = ratings_shuf.iloc[:int(0.8 * n)].copy()
    val   = ratings_shuf.iloc[int(0.8 * n):int(0.9 * n)].copy()
    test  = ratings_shuf.iloc[int(0.9 * n):].copy()
    print(f"\n  Split : train={len(train):,} | val={len(val):,} | test={len(test):,}")

    # [C5] Courbe RMSE(k) pour détecter le surapprentissage
    print("\n" + "=" * 60)
    print("  SÉLECTION DE K — COURBE RMSE")
    print("=" * 60)
    # Build R_train and get its maps
    R_train, um_train, mm_train = build_sparse_matrix(train)

    # Build R_val using the maps from R_train. This ensures consistent indexing.
    # Ratings in 'val' that involve users or movies NOT present in 'train' will be ignored.
    R_val_for_rmse, _, _ = build_sparse_matrix(val, user_map_input=um_train, movie_map_input=mm_train)

    curve_df = rmse_vs_k_curve(R_train, R_val_for_rmse, k_values=[5, 10, 20, 40])

    # Entraînement principal
    print("\n" + "=" * 60)
    print("  ENTRAÎNEMENT SYSTÈME HYBRIDE")
    print("=" * 60)
    rec = StreamingRecommender(k=10, n_iter=15, reg_lambda=0.1, top_k=20, alpha=0.30)
    rec.fit(train, movies, users)

    # [C2] Calibration du poids alpha sur validation
    print("\n" + "=" * 60)
    print("  CALIBRATION PONDÉRATION α (Grid Search)")
    print("=" * 60)
    best_alpha, calib_df = calibrate_weights(rec, val)
    rec.alpha = best_alpha
    print(calib_df.to_string(index=False))

    # Test recommandation
    print("\n" + "=" * 60)
    print("  RECOMMANDATIONS HYBRIDES — USER 1")
    print("=" * 60)
    recs = rec.recommend(user_id=1, K=10)
    for i, r in enumerate(recs, 1):
        print(f"  {i:>2}. [{r['score_hybrid']:.3f}] {r['title']}  "
              f"(ALS={r['score_als']:.3f})")

    # [C3] Test notation + mise à jour latence
    print("\n" + "=" * 60)
    print("  TEST LATENCE — NOTATION + RECOMMANDATION")
    print("=" * 60)
    t0 = time.time()
    rec.rate_movie(user_id=1, movie_id=2355, rating=5)
    recs_after = rec.recommend(user_id=1, K=5)
    print(f"  Reco mise à jour en {(time.time()-t0)*1000:.1f} ms total")
    for i, r in enumerate(recs_after, 1):
        print(f"  {i:>2}. [{r['score_hybrid']:.3f}] {r['title']}")

    # Cold Start
    print("\n" + "=" * 60)
    print("  COLD START — GENRE ['Action', 'Sci-Fi']")
    print("=" * 60)
    for i, r in enumerate(rec.recommend_cold_start(genres=["Action", "Sci-Fi"], K=5), 1):
        print(f"  {i:>2}. {r[1]}  (score={r[2]:.3f})")

    # [C5] Évaluation rigoureuse
    eval_df = evaluate_full(rec, test, Ks=[5, 10, 20], n_sample=300)

    # [C7] NCF
    print("\n" + "=" * 60)
    print("  ESQUISSE NEURAL COLLABORATIVE FILTERING")
    print("=" * 60)
    ncf = NCFSketch(
        n_users=ratings["user_id"].nunique(),
        n_movies=ratings["movie_id"].nunique(),
        k_mf=20, k_mlp=64
    )
    ncf.summary()
    sample_pred = ncf.predict(0, 0)
    print(f"\n  Prédiction exemple (non entraîné) user=0, film=0 : {sample_pred:.3f}")
    print("  → À entraîner via PyTorch avec BPR loss ou MSE loss")

    print("\n" + "=" * 60)
    print("  SYSTÈME OPÉRATIONNEL ✅")
    print("=" * 60)